# web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: petclinic-web-service
  namespace: petclinic
  annotations:
   cloud.google.com/neg: '{"ingress": true}'

spec:
  type: ClusterIP # ingress 사용 하니까 ClusterIP로 변경
  selector:
    app: petclinic-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
